version: 0.0
os: linux
files:
  - source: /tmp/build-artifacts/bcca   # the artifacts folder from build.sh
    destination: /var/www/bcca          # the destiation on the ec2 instance
#hooks:
#  ApplicationStart:
#    - location: scripts/restart-website.sh
#      timeout: 300